# Generated by Django 5.1.6 on 2025-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=255)),
                ('Esal', models.FloatField()),
                ('role', models.CharField(max_length=100)),
                ('jdate', models.DateField()),
            ],
        ),
    ]
