# Generated by Django 5.1.3 on 2024-11-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0002_alter_basics_inserttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basics',
            name='about',
        ),
        migrations.RemoveField(
            model_name='basics',
            name='dateOfJoin',
        ),
        migrations.RemoveField(
            model_name='basics',
            name='email',
        ),
        migrations.RemoveField(
            model_name='basics',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='basics',
            name='insertTime',
        ),
        migrations.RemoveField(
            model_name='basics',
            name='married',
        ),
        migrations.RemoveField(
            model_name='basics',
            name='salary',
        ),
        migrations.AlterField(
            model_name='basics',
            name='lastName',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
