# Generated by Django 5.1.3 on 2024-11-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='hod',
            new_name='head',
        ),
    ]
