# Generated by Django 5.1.4 on 2025-01-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="betch",
            new_name="batch",
        ),
    ]
